<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-05T15:38:38 PST" name="Suite" finished-at="2021-03-05T15:39:37 PST" duration-ms="58887">
    <groups>
    </groups>
    <test started-at="2021-03-05T15:38:38 PST" name="Test" finished-at="2021-03-05T15:39:37 PST" duration-ms="58887">
      <class name="io.nirmata.tests.AddDeploymentToApplication">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.nirmata.tests.AddDeploymentToApplication@34f7cfd9]" started-at="2021-03-05T15:38:38 PST" name="setUp" finished-at="2021-03-05T15:38:54 PST" duration-ms="15108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="CreateApp(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:io.nirmata.tests.AddDeploymentToApplication@34f7cfd9]" started-at="2021-03-05T15:38:54 PST" name="CreateApp" finished-at="2021-03-05T15:39:36 PST" duration-ms="42362" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[alexandru@nirmata.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[nirmata01]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[alex05]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[abcd-app]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[abcd-deployment]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[Docker Hub]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[nirmata/hello-world]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[green]]>
              </value>
            </param>
            <param index="9">
              <value>
                <![CDATA[IfNotPresent]]>
              </value>
            </param>
            <param index="10">
              <value>
                <![CDATA[java]]>
              </value>
            </param>
            <param index="11">
              <value>
                <![CDATA[VAR]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at io.nirmata.tests.AddDeploymentToApplication.CreateApp(AddDeploymentToApplication.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateApp -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:io.nirmata.tests.AddDeploymentToApplication@34f7cfd9]" started-at="2021-03-05T15:39:36 PST" name="tearDown" finished-at="2021-03-05T15:39:37 PST" duration-ms="901" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.nirmata.tests.AddDeploymentToApplication -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
